package rules
 
import co.com.ceiba.cds.drools.model.Product

rule "Offer for Shirt"
	when 
		productObject: Product(type=="shirt")
	then
		double precio = 32000;
		productObject.setDiscount(0.18);
		productObject.setPrice(precio - (precio * productObject.getDiscount()));
	end
rule "Offer for Pants"
	when 
		productObject: Product(type=="pants")
	then
		double precio = 100450;
		productObject.setDiscount(0.14);
		productObject.setPrice(precio - (precio * productObject.getDiscount()));
	end